---
AWSTemplateFormatVersion: '2010-09-09'
Description: serposcope_instance
Resources:
  # インスタンス
  Instance:
    Type: "AWS::EC2::Instance"
    Properties:
      AvailabilityZone: us-east-2a
      ImageId: ami-c55673a0
      InstanceType: t2.nano
      KeyName: xxx
      SecurityGroups:
      - default
      - !Ref InstanceSecurityGroup

  # セキュリティーグループ
  InstanceSecurityGroup:
    Type: "AWS::EC2::SecurityGroup"
    Properties:
      GroupDescription: serposcope_security
      SecurityGroupIngress:
        -
          IpProtocol: "tcp"
          FromPort: "22"
          ToPort: "22"
          CidrIp: "xxxx"
        -
          IpProtocol: "tcp"
          FromPort: "7134"
          ToPort: "7134"
          CidrIp: "0.0.0.0/0"
        -
          IpProtocol: "tcp"
          FromPort: "80"
          ToPort: "80"
          CidrIp: "xxx"

  # 固定IP
  EIP:
    Type: "AWS::EC2::EIP"
    Properties:
      InstanceId:
        Ref : Instance
